[tool.poetry]
name = "supply-chain-common"
version = "0.1.0"
description = "Common dependencies for supply chain microservices"
authors = ["Andres Cox <andreshcox@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.110.0"
uvicorn = "^0.29.0"
confluent-kafka = "^2.3.0"
pydantic = "^2.6.1"
logging_utils = {path = "libs/logging_utils"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"