apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fraud-detection-service
  labels:
    app: fraud-detection-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-detection-service
  template:
    metadata:
      labels:
        app: fraud-detection-service
      annotations:
        statefulset.kubernetes.io/pod-name: fraud-detection-service-${HOSTNAME}
    spec:
      containers:
      - name: fraud-detection-service
        image: fraud-detection:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-broker:9092"
        - name: KAFKA_CONSUMER_GROUP
          value: "fraud-detection-group"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-service
spec:
  selector:
    app: fraud-detection-service
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP