apiVersion: v1
kind: Pod
metadata:
  name: kafka-client
  labels:
    app: kafka-client
spec:
  restartPolicy: Always
  initContainers:
    - name: create-kafka-topics
      image: bitnami/kafka:4.0.0-debian-12-r0
      command:
        - sh
        - -c
        - |
          echo "Creating Kafka topics..."
          kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic orders.created --replication-factor 1 --partitions 1
          kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic locations.updated --replication-factor 1 --partitions 1
          kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic alerts.fraud --replication-factor 1 --partitions 1
          echo "Done creating topics"
  containers:
    - name: kafka-client
      image: bitnami/kafka:4.0.0-debian-12-r0
      command:
        - sleep
        - infinity